name: jmas_movil_lecturas
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2 #WEB
  shared_preferences: ^2.3.3 #Guardar token
  intl: ^0.19.0 #Fecha
  geolocator: ^14.0.1 #Localicaión
  image_picker: ^1.1.2 #Seleccionar imagen
  path_provider: ^2.1.5 #Provider
  connectivity_plus: ^6.1.4 #Conexión
  sqflite: ^2.4.2 #DB
  flutter_svg: ^2.2.0 #SVG
  signature: ^6.3.0 #Firma

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  
  uses-material-design: true

  
  assets:
    - assets/svg/
    - assets/jpg/
    - assets/png/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
